### ISSUE TITLE
Multiple Set-Cookies in one response

### ISSUE THREAD

**Issue by pvanloo** [unosquare/embedio#254]
**Describe the bug**
Multiple calls to Response.Headers.Add() with a Set-Cookie header results in a comma-seperated value. 

I believe this unwanted behaviour as this is not supported by modern browsers according to this [StackOverflow](https://stackoverflow.com/questions/51564395/add-multiple-cookies-to-clients-web-browser-via-httplistenerresponse) question.

Additionally, using Response.AddHeader() only holds the last-value added.

**To Reproduce**
1. Create a new controller
2. Add multiple calls to Response.Headers.Add() with a Set-Cookie name
3. Observe Response.Headers["Set-Cookie"] as comma-separated list

**Expected behavior**
Ideally, for each Set-Cookie added, a new header item should be created.
Else, an option to append header items.

**Screenshots**
Comma-separated Set-Cookie header
![image](https://user-images.githubusercontent.com/26272906/54609958-43665900-4a54-11e9-8b8a-f8d47c8aca53.png)

**Smartphone (please complete the following information):**
Xamarin App running on Samsung S8 with Android 8.0
Xamarin App running on simulated iPhone XS Max iOS 12.1

**Additional context**

**Comment by geoperez** [comment]
I created a new branch for this issue.

**Comment by pvanloo** [comment]
Hi @geoperez, thanks for making the time to check this.

I've managed to test this but I'm still seeing some odd behaviour:

This is the request that I'm passing to the Set-Cookie header:

![image](https://user-images.githubusercontent.com/26272906/55859500-7e9b0a00-5b72-11e9-82df-48a299c14521.png)

EmbedIO correctly splits the headers (as issue states) but doesn't parse the cookie correctly (path removed).

![image](https://user-images.githubusercontent.com/26272906/55859508-822e9100-5b72-11e9-9abd-c4aee9a4b3b7.png)


I've also tried splitting and adding two Set-Cookie headers myself, but the path is still lost.

**Comment by geoperez** [comment]
How are you creating the cookie?

**Comment by pvanloo** [comment]
It's being set as a Set-Cookie header (see first screenshot).

The second screenshot is what I'm viewing in the browser's developer console.

**Comment by geoperez** [comment]
I know what is the issue. The default `ToString()` response of Cookie just returns name=value without the additional properties.

I'm going to change that.

**Comment by geoperez** [comment]
I updated the branch and with the following code:

```
Response.Headers.Add("Set-Cookie", "test=val;Path=/");
Response.SetCookie(new Cookie("test2", "val2", "/"));
```

I'm getting this:

![image](https://user-images.githubusercontent.com/1775792/55888317-c589ff00-5b74-11e9-8a4c-65a53d416728.png)

But I have a doubt regarding if I should send lowercase properties...

**Comment by pvanloo** [comment]
I think the properties can be both upper and lower case [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)

However I think there might need to be a space after the ';'

Also still not every property is being shown;

Direct connection to a website
![image](https://user-images.githubusercontent.com/26272906/55937276-def47f00-5c38-11e9-9383-03c73b9c3932.png)

Connection to EmbedIO
![image](https://user-images.githubusercontent.com/26272906/55937309-f3387c00-5c38-11e9-8311-474987a33d73.png)

**Comment by geoperez** [comment]
I did some changes to the Cookie Response. Please let me know.

**Comment by pvanloo** [comment]
I've noticed switched httponly/secure;

https://github.com/unosquare/embedio/commit/cf474141a83c0e36e4a0672f3cb67f96151b9d4d#r33141301

https://github.com/unosquare/embedio/commit/cf474141a83c0e36e4a0672f3cb67f96151b9d4d#r33141302

**Comment by geoperez** [comment]
Done!

**Comment by geoperez** [comment]
@pvanloo should I publish the changes now?

**Comment by pvanloo** [comment]
So far it looks good to me, thanks!

**Comment by geoperez** [comment]
I just published the new Nuget v2.5.0. Closing this issue.
