### ISSUE TITLE
Reading request with `Transfer-Encoding: chunked` not working

### ISSUE THREAD

**Issue by rocketraman** [unosquare/embedio#320]
**Describe the bug**
A request to an embed.io server with a chunked transfer encoding does not read the correct input data.

**To Reproduce**
Start an embed/io server that reads some input and responds with the sha1 hash.

```
[WebApiHandler(HttpVerbs.Post, "/sha1")]
public async Task<bool> Sha1Hash()
{
    return await HttpContext.StringResponseAsync(Hash(Request.InputStream));
}

static string Hash(Stream input)
{
    var hash = new SHA1Managed().ComputeHash(input);
    return string.Concat(hash.Select(b => b.ToString("x2")));
}
```

Call this server, passing the `Content-Length`:

```
$ curl -H "Content-Type: application/octet-stream" --data-binary @foo.pdf http://localhost:7071/sha1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7071 (#0)
> POST /sha1 HTTP/1.1
> Host: localhost:7071
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Length: 9978
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Expires: Mon, 26 Jul 1997 05:00:00 GMT
< Last-Modified: Thu, 18 Jul 2019 18:56:49 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Content-Type: application/json; charset=utf-8
< Server: embedio/2.0
< Date: Thu, 18 Jul 2019 18:56:49 GMT
< Content-Length: 40
< Keep-Alive: timeout=15,max=100
< 
* Connection #0 to host localhost left intact
7e930f7ad56ffac55ff969946cfc9c6764d77997
```

The correct SHA1 hash is received. Now, call it again using the chunked transfer encoding:

```
$ curl -v -H "Content-Type: application/octet-stream" -H "Transfer-Encoding: chunked" --data-binary @foo.pdf http://localhost:7071/sha1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7071 (#0)
> POST /sha1 HTTP/1.1
> Host: localhost:7071
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/octet-stream
> Transfer-Encoding: chunked
> Expect: 100-continue
> 
* Done waiting for 100-continue
* Signaling end of chunked upload via terminating chunk.
< HTTP/1.1 200 OK
< Expires: Mon, 26 Jul 1997 05:00:00 GMT
< Last-Modified: Thu, 18 Jul 2019 19:02:28 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Content-Type: application/json; charset=utf-8
< Server: embedio/2.0
< Date: Thu, 18 Jul 2019 19:02:28 GMT
< Content-Length: 40
< Keep-Alive: timeout=15,max=100
< 
* Connection #0 to host localhost left intact
da39a3ee5e6b4b0d3255bfef95601890afd80709
```

and note now the sha1 hash is incorrect.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Anything

**Comment by geoperez** [comment]
Hi, quick question. Can you test the same use case with the new EmbedIO 3?

**Comment by rocketraman** [comment]
> Hi, quick question. Can you test the same use case with the new EmbedIO 3?

@geoperez Sorry, no. I briefly tried to convert my app from 2 to 3-preview8 but had no success. I get a null reference on `webApi.registerController`.

**Comment by geoperez** [comment]
Yeah, that is fixed. Please use preview10.

**Comment by rocketraman** [comment]
@geoperez  I didn't see preview10 in nuget, but preview9 solved the null ref issue. I can confirm that version has the same problem.

**Comment by rdeago** [comment]
As a matter of fact, the HTTP listener and related classes is probably the only part of EmbedIO that has seen little to no change between v2 and v3.

@rocketraman does it happen with both kinds of HTTP listener? Could you try initializing you server with `HttpListenerMode.Microsoft`, then with `HttpListenerMode.EmbedIO`, and tell us whether the observed misbehavior happens with both of them, or just one, and if so, which one? Thanks a lot.

**Comment by rocketraman** [comment]
@rdeago  With both v2 and v3 + `HttpListenerMode.Microsoft`, I get the following error when calling `Wait` on the result of `RunAsync`, and note that `RunAsync` doesn't actually seem to start a server -- the logs just show "Cleaning up":

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MyServer.Main(String[] args) in H:\source\MyServer\WebApi.cs:line 27

Inner Exception 1:
HttpListenerException: Access is denied
```

**Comment by rocketraman** [comment]
Ok, I got past that error via https://stackoverflow.com/questions/4019466/httplistener-access-denied... however, I still get a 503 error from the server when using the Microsoft listener mode.

**Comment by rdeago** [comment]
Yes, Microsoft's HttpListener can be a major pain in the rear bumper.

I've found a couple StackOverflow questions [link 1](https://stackoverflow.com/questions/8142396/what-causes-a-httplistener-http-503-error) [link 2](https://stackoverflow.com/questions/26412602/httplistener-server-returns-an-error-503-service-unavailable) that may be of help. You probably found them even before I read your comment, but just in case.

In the meantime I'm going to investigate the issue with EmbedIO's own HttpListener.

**Comment by rdeago** [comment]
Looks like transfer encoding in requests is not supported at all with `HttpListenerMode.EmbedIO`. Sorry for the bad news.

You may have success with `HttpListenerMode.Microsoft` (once it decides it's bugged you enough and starts behaving), as apparently .NET Core (at least) supports chunked encoding in requests.

**Comment by rocketraman** [comment]
I finally got it working with the Microsoft listener [1], and as you surmised in your last message, the Microsoft listener does work correctly with a chunked encoding. However, from a deployment perspective having to set ACLs and such with the MS listener is basically a non-starter. Is there any plan to add support for this in the EmbedIO listener?

[1] So a URL prefix of `$"http://*:{port}/` does not work (even with the matching netacl added), while a URL prefix of `$"http://+:{port}/` *does* work (with the matching netacl added). Crazy.

**Comment by rdeago** [comment]
The EmbedIO listener is basically a copy of an old version of Mono's HttpListener, with WebSocket support (which Mono didn't have at the time) copied from WebSocketSharp. It was the right choice (read: basically the _only_ choice) at the time, but now we'd be better off copying code from CoreFX (as Mono now does, too). There are also other fully-managed open source HTTP servers. Once EmbedIO v3.0 is stable, we'll start evaluating choices for the new listener, but unfortunately it's too early to give a time frame.
